### ISSUE TITLE
Getting error while using vega library (DICOM_2_egsinp)

### ISSUE THREAD

**Issue by munir001** [project-eutopia/vega#17] opened 2022-09-27 20:45 UTC
Hi Chris, 
We're using an old version of vega library to convert dicom files to egsinp files (DICOM_2_egsinp). Recently, we updated the cluster and got following error while running DICOM_2_egsinp script,
**/usr/bin/ld: Vega_DICOM_Library//libvega.a(VEGA_Classes.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status**
To resolve this error we installed the new version of vega library from github and included the PIE flag in CMakeLists.txt file. Now, when we run DICOM_2_egsinp script we get following error,
**undefined reference to ‘CPP_Sequence::item(unsigned int) const’ etc**
In DICOM_2_egsinp.cpp file, we're using #include line for VEGA_Classes.h for the old version, but we can’t find such file for the new Vega. Could you please let us know how to get rid of this error. Thanks.

**Comment by project-eutopia** [comment] 2022-09-28 00:19
Hello Munir,

Thanks for using this library! I will try to help you debug this compile error.

Is the file DICOM_2_egsinp.cpp an internal file that you wrote which uses the library? If so, could you help me reproduce this error locally? To do that there are a few options:
- Upload a Dockerfile and required files somewhere to reproduce the error exactly. There is a Dockerfile in this github repo if that helps get you started (see also the `.travis.yml` file for the commands used to install and run the Docker image)
- If you cannot figure out how to get Docker working to make a container, then you can try just uploading the files you are trying to compile somewhere, and share with me the commands that caused this issue (what architecture are you compiling on?)
- If the files are sensitive, you can try removing as much of the private code you can while still getting the same compile error and share that file ("minimal reproducible example", which is good practice anyway as it removes the parts of the code that are not relevant to the error, making it easier to debug).

Thanks!

**Comment by project-eutopia** [comment] 2022-10-31 13:10
Closing this issue. Offline it was determined that this error was due to trying to use this version of the Vega library that is on Github, with code that expects an older legacy version of Vega that is not in this repository and has very different APIs.

**Closed as completed by project-eutopia** 2022-10-31 13:10 UTC
